Repository Teammanagers/BackEnd, pull requests merged in 2024-08, with the labels that each got.

#27 [Feature] 팀 도메인 구현 완료
  src/main/java/kr/teammanagers/alarm/domain/Alarm.java
  src/main/java/kr/teammanagers/calendar/domain/Calendar.java
  src/main/java/kr/teammanagers/calendar/domain/TeamCalendar.java
  src/main/java/kr/teammanagers/member/application/MemberService.java
  src/main/java/kr/teammanagers/member/dto/response/GetMemberTeam.java
  src/main/java/kr/teammanagers/notice/application/NoticeService.java
  src/main/java/kr/teammanagers/notice/dto/response/GetNoticeRecent.java
  src/main/java/kr/teammanagers/notice/presentation/NoticeController.java
  src/main/java/kr/teammanagers/notice/repository/NoticeRepository.java
  src/main/java/kr/teammanagers/schedule/domain/AvailableTime.java
  src/main/java/kr/teammanagers/schedule/domain/TimeTable.java
  src/main/java/kr/teammanagers/team/application/TeamService.java
  src/main/java/kr/teammanagers/team/constant/TeamConstant.java
  src/main/java/kr/teammanagers/team/domain/Team.java
  src/main/java/kr/teammanagers/team/dto/RegisterCommentDto.java
  src/main/java/kr/teammanagers/team/dto/SimpleTeamMemberDto.java
  src/main/java/kr/teammanagers/team/dto/TeamDto.java
  src/main/java/kr/teammanagers/team/dto/TeamMemberDto.java
  src/main/java/kr/teammanagers/team/dto/request/CreateTeam.java
  src/main/java/kr/teammanagers/team/dto/request/CreateTeamComment.java
  src/main/java/kr/teammanagers/team/dto/request/CreateTeamPassword.java
  src/main/java/kr/teammanagers/team/dto/response/CreateTeamResult.java
  src/main/java/kr/teammanagers/team/dto/response/GetTeam.java
  src/main/java/kr/teammanagers/team/dto/response/GetTeamMember.java
  src/main/java/kr/teammanagers/team/dto/response/UpdateTeamEndResult.java
  src/main/java/kr/teammanagers/team/presentation/TeamController.java
  src/main/java/kr/teammanagers/team/repository/TeamRepository.java
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#29 [Feature] 멤버 클래스 providerId 변수 및 findByProviderId 메소드 구현
  src/main/java/kr/teammanagers/member/domain/Member.java
  src/main/java/kr/teammanagers/member/repository/MemberRepository.java
Labels: :sparkles: Feature, :yellow_circle: 현수

#30 [Feature] 캘린더 도메인 구현 완료
  src/main/java/kr/teammanagers/calendar/application/CalendarCommandService.java
  src/main/java/kr/teammanagers/calendar/application/CalendarCommandServiceImpl.java
  src/main/java/kr/teammanagers/calendar/application/CalendarQueryService.java
  src/main/java/kr/teammanagers/calendar/application/CalendarQueryServiceImpl.java
  src/main/java/kr/teammanagers/calendar/domain/Calendar.java
  src/main/java/kr/teammanagers/calendar/domain/TeamCalendar.java
  src/main/java/kr/teammanagers/calendar/dto/CalendarDetailDto.java
  src/main/java/kr/teammanagers/calendar/dto/CalendarDto.java
  src/main/java/kr/teammanagers/calendar/dto/CalendarListDto.java
  src/main/java/kr/teammanagers/calendar/dto/request/CreateCalendar.java
  src/main/java/kr/teammanagers/calendar/dto/request/UpdateCalendar.java
  src/main/java/kr/teammanagers/calendar/dto/response/GetCalendar.java
  src/main/java/kr/teammanagers/calendar/dto/response/GetComingCalendarList.java
  src/main/java/kr/teammanagers/calendar/dto/response/GetSimpleCalendarList.java
  src/main/java/kr/teammanagers/calendar/presentation/CalendarRestController.java
  src/main/java/kr/teammanagers/calendar/repository/CalendarRepository.java
  src/main/java/kr/teammanagers/calendar/repository/TeamCalendarQueryDsl.java
  src/main/java/kr/teammanagers/calendar/repository/TeamCalendarQueryDslImpl.java
  src/main/java/kr/teammanagers/calendar/repository/TeamCalendarRepository.java
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/team/repository/TeamManageRepository.java
  src/main/java/kr/teammanagers/term/presentation/TermRestController.java
Labels: :sparkles: Feature, :recycle: Refactor, :large_blue_circle: 희수

#37 [Feat] 인증/인가 구현
  build.gradle
  src/main/java/kr/teammanagers/auth/controller/AuthController.java
  src/main/java/kr/teammanagers/auth/dto/OAuth2UserInfo.java
  src/main/java/kr/teammanagers/auth/dto/PrincipalDetails.java
  src/main/java/kr/teammanagers/auth/dto/TokenDto.java
  src/main/java/kr/teammanagers/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/kr/teammanagers/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/kr/teammanagers/auth/handler/OAuth2FailureHandler.java
  src/main/java/kr/teammanagers/auth/handler/OAuth2SuccessHandler.java
  src/main/java/kr/teammanagers/auth/jwt/domain/MemberToken.java
  src/main/java/kr/teammanagers/auth/jwt/repository/MemberTokenRepository.java
  src/main/java/kr/teammanagers/auth/service/CustomOAuth2UserService.java
  src/main/java/kr/teammanagers/auth/service/TokenService.java
  src/main/java/kr/teammanagers/global/config/SecurityConfig.java
  src/main/java/kr/teammanagers/global/constant/TokenKey.java
  src/main/java/kr/teammanagers/global/exception/AuthException.java
  src/main/java/kr/teammanagers/global/exception/CustomException.java
  src/main/java/kr/teammanagers/global/exception/ErrorCode.java
  src/main/java/kr/teammanagers/global/exception/ErrorResponse.java
  src/main/java/kr/teammanagers/global/exception/GlobalExceptionHandler.java
  src/main/java/kr/teammanagers/global/exception/TokenAuthenticationFilter.java
  src/main/java/kr/teammanagers/global/exception/TokenException.java
  src/main/java/kr/teammanagers/global/exception/TokenExceptionFilter.java
  src/main/java/kr/teammanagers/global/provider/TokenProvider.java
  src/main/java/kr/teammanagers/member/domain/Member.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: :sparkles: Feature, :yellow_circle: 현수

#35 [Feature] 스케줄 도메인 구현 완료
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/schedule/application/ScheduleCommandService.java
  src/main/java/kr/teammanagers/schedule/application/ScheduleCommandServiceImpl.java
  src/main/java/kr/teammanagers/schedule/application/ScheduleQueryService.java
  src/main/java/kr/teammanagers/schedule/application/ScheduleQueryServiceImpl.java
  src/main/java/kr/teammanagers/schedule/domain/Schedule.java
  src/main/java/kr/teammanagers/schedule/domain/TimeTable.java
  src/main/java/kr/teammanagers/schedule/dto/ScheduleDto.java
  src/main/java/kr/teammanagers/schedule/dto/request/CreateSchedule.java
  src/main/java/kr/teammanagers/schedule/dto/request/UpdateSchedule.java
  src/main/java/kr/teammanagers/schedule/dto/response/GetTeamSchedule.java
  src/main/java/kr/teammanagers/schedule/presentation/ScheduleRestController.java
  src/main/java/kr/teammanagers/schedule/repository/ScheduleRepository.java
Labels: :sparkles: Feature, :large_blue_circle: 희수

#44 [BUG] 토큰 발급 문제 해결
  src/main/java/kr/teammanagers/auth/Application/CustomOAuth2UserService.java
  src/main/java/kr/teammanagers/auth/Application/CustomUserDetailsService.java
  src/main/java/kr/teammanagers/auth/Application/TokenService.java
  src/main/java/kr/teammanagers/auth/dto/CustomUserDetails.java
  src/main/java/kr/teammanagers/auth/dto/PrincipalDetails.java
  src/main/java/kr/teammanagers/auth/presentation/AuthController.java
  src/main/java/kr/teammanagers/global/config/SecurityConfig.java
  src/main/java/kr/teammanagers/global/provider/TokenProvider.java
Labels: :bug: Bug, :yellow_circle: 현수

#41 [Feature] 팀 도메인 예외 처리 구현
  build.gradle
  src/main/java/kr/teammanagers/TeammanagersApplication.java
  src/main/java/kr/teammanagers/common/payload/code/constant/ValidatorErrorConstant.java
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/tag/constant/TagErrorConstant.java
  src/main/java/kr/teammanagers/tag/exception/validator/TagMaxSize.java
  src/main/java/kr/teammanagers/tag/exception/validator/TagMaxSizeValidator.java
  src/main/java/kr/teammanagers/team/application/TeamCommandService.java
  src/main/java/kr/teammanagers/team/application/TeamCommandServiceImpl.java
  src/main/java/kr/teammanagers/team/application/TeamQueryService.java
  src/main/java/kr/teammanagers/team/application/TeamQueryServiceImpl.java
  src/main/java/kr/teammanagers/team/constant/TeamErrorConstant.java
  src/main/java/kr/teammanagers/team/dto/RegisterCommentDto.java
  src/main/java/kr/teammanagers/team/dto/request/CreateTeam.java
  src/main/java/kr/teammanagers/team/dto/request/CreateTeamComment.java
  src/main/java/kr/teammanagers/team/dto/request/CreateTeamPassword.java
  src/main/java/kr/teammanagers/team/exception/validator/TeamMemberSize.java
  src/main/java/kr/teammanagers/team/exception/validator/TeamMemberSizeValidator.java
  src/main/java/kr/teammanagers/team/presentation/TeamController.java
  src/main/java/kr/teammanagers/team/repository/TeamManageRepository.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#45 [Feature] 환경변수 업데이트
  src/main/java/kr/teammanagers/global/provider/TokenProvider.java
  src/main/resources/application-oauth.yml
Labels: :sparkles: Feature, :yellow_circle: 현수

#48 [Refactor] 팀/유저 프로필 업로드, 조회 기능 리팩토링
  src/main/java/kr/teammanagers/auth/dto/OAuth2UserInfo.java
  src/main/java/kr/teammanagers/auth/dto/PrincipalDetails.java
  src/main/java/kr/teammanagers/global/config/SecurityConfig.java
  src/main/java/kr/teammanagers/global/provider/AmazonS3Provider.java
  src/main/java/kr/teammanagers/global/provider/TokenProvider.java
  src/main/java/kr/teammanagers/member/application/MemberService.java
  src/main/java/kr/teammanagers/member/domain/Member.java
  src/main/java/kr/teammanagers/member/dto/response/GetProfile.java
  src/main/java/kr/teammanagers/member/presentation/MemberController.java
  src/main/java/kr/teammanagers/team/application/TeamCommandServiceImpl.java
  src/main/java/kr/teammanagers/team/application/TeamQueryServiceImpl.java
  src/main/java/kr/teammanagers/team/domain/Team.java
  src/main/java/kr/teammanagers/team/dto/TeamDto.java
  src/main/java/kr/teammanagers/team/dto/TeamMemberDto.java
  src/main/java/kr/teammanagers/team/dto/request/CreateTeam.java
  src/main/java/kr/teammanagers/team/dto/response/GetTeam.java
Labels: :recycle: Refactor, :green_circle: 승민

#50 [Feat] 팀 자료 기능 구현
  build.gradle
  src/main/java/kr/teammanagers/common/AuditingField.java
  src/main/java/kr/teammanagers/global/config/MultipartConfig.java
  src/main/java/kr/teammanagers/global/provider/AmazonS3ProviderV2.java
  src/main/java/kr/teammanagers/global/util/AmazonS3Helper.java
  src/main/java/kr/teammanagers/storage/application/StorageCommandService.java
  src/main/java/kr/teammanagers/storage/application/StorageCommandServiceImpl.java
  src/main/java/kr/teammanagers/storage/application/StorageQueryService.java
  src/main/java/kr/teammanagers/storage/application/StorageQueryServiceImpl.java
  src/main/java/kr/teammanagers/storage/domain/TeamData.java
  src/main/java/kr/teammanagers/storage/dto/StorageDto.java
  src/main/java/kr/teammanagers/storage/dto/request/CreateStorageRequest.java
  src/main/java/kr/teammanagers/storage/dto/response/StorageResponse.java
  src/main/java/kr/teammanagers/storage/presentation/StorageController.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :yellow_circle: 현수

#51 [Feat] 팀 자료 댓글 구현
  src/main/java/kr/teammanagers/feedback/application/FeedbackCommandService.java
  src/main/java/kr/teammanagers/feedback/application/FeedbackCommandServiceImpl.java
  src/main/java/kr/teammanagers/feedback/application/FeedbackQueryService.java
  src/main/java/kr/teammanagers/feedback/application/FeedbackQueryServiceImpl.java
  src/main/java/kr/teammanagers/feedback/dto/request/CreateFeedbackRequest.java
  src/main/java/kr/teammanagers/feedback/dto/response/FeedbackResponse.java
  src/main/java/kr/teammanagers/feedback/presentation/FeedbackController.java
  src/main/java/kr/teammanagers/feedback/repository/FeedbackRepository.java
  src/main/java/kr/teammanagers/storage/domain/TeamData.java
Labels: :sparkles: Feature, :yellow_circle: 현수

#54 [Refactor] 컨트롤러 인증 추가 및 API 수정
  src/main/java/kr/teammanagers/alarm/presentation/AlarmRestController.java
  src/main/java/kr/teammanagers/calendar/presentation/CalendarRestController.java
  src/main/java/kr/teammanagers/schedule/presentation/ScheduleRestController.java
  src/main/java/kr/teammanagers/term/application/TermCommandService.java
  src/main/java/kr/teammanagers/term/application/TermCommandServiceImpl.java
  src/main/java/kr/teammanagers/term/presentation/TermRestController.java
  src/main/java/kr/teammanagers/todo/application/TodoCommandService.java
  src/main/java/kr/teammanagers/todo/application/TodoCommandServiceImpl.java
  src/main/java/kr/teammanagers/todo/presentation/TodoRestController.java
Labels: :recycle: Refactor, :large_blue_circle: 희수

#55 [Feature] 피드백 수정 / 삭제 구현 및 Request 방식 수정
  src/main/java/kr/teammanagers/feedback/application/FeedbackCommandService.java
  src/main/java/kr/teammanagers/feedback/application/FeedbackCommandServiceImpl.java
  src/main/java/kr/teammanagers/feedback/application/FeedbackQueryService.java
  src/main/java/kr/teammanagers/feedback/application/FeedbackQueryServiceImpl.java
  src/main/java/kr/teammanagers/feedback/domain/Feedback.java
  src/main/java/kr/teammanagers/feedback/dto/FeedbackDto.java
  src/main/java/kr/teammanagers/feedback/dto/request/CreateFeedbackRequest.java
  src/main/java/kr/teammanagers/feedback/dto/request/UpdateFeedbackRequest.java
  src/main/java/kr/teammanagers/feedback/presentation/FeedbackController.java
Labels: :sparkles: Feature, :yellow_circle: 현수

#63 [Refactor] 사용자, 메모, 공지, 태그 도메인 서비스 레이어 분리 및 CORS 긴급 수정
  src/main/java/WebConfig.java
  src/main/java/kr/teammanagers/global/config/SecurityConfig.java
Labels: :bug: Bug, :green_circle: 승민

#65 Fix: CORS 설정 수정
  src/main/java/kr/teammanagers/global/config/SecurityConfig.java
Labels: :bug: Bug, :green_circle: 승민

#69 [Feature] 마이페이지 투두리스트 조회 API 구현
  src/main/java/kr/teammanagers/member/application/MemberQueryService.java
  src/main/java/kr/teammanagers/member/application/MemberQueryServiceImpl.java
  src/main/java/kr/teammanagers/member/dto/response/GetMyTodoList.java
  src/main/java/kr/teammanagers/member/presentation/MemberController.java
  src/main/java/kr/teammanagers/todo/dto/MyTodoListDto.java
Labels: :sparkles: Feature, :green_circle: 승민

#72 [Fix] 스케줄 DDL 및 투두 진행도 계산 로직 수정
  src/main/java/kr/teammanagers/schedule/domain/Schedule.java
  src/main/java/kr/teammanagers/todo/application/TodoQueryServiceImpl.java
Labels: :bug: Bug, :large_blue_circle: 희수

#74 [Feature] 팀 투두리스트 조회 응답 필드 추가
  src/main/java/kr/teammanagers/todo/application/TodoQueryService.java
  src/main/java/kr/teammanagers/todo/application/TodoQueryServiceImpl.java
  src/main/java/kr/teammanagers/todo/dto/response/GetTodoList.java
  src/main/java/kr/teammanagers/todo/presentation/TodoRestController.java
Labels: :sparkles: Feature, :large_blue_circle: 희수

#75 [Feature] 공지, 메모 도메인 예외 처리 구현
  src/main/java/kr/teammanagers/memo/dto/request/CreateMemo.java
  src/main/java/kr/teammanagers/memo/dto/request/UpdateMemo.java
  src/main/java/kr/teammanagers/memo/presentation/MemoController.java
  src/main/java/kr/teammanagers/notice/application/command/NoticeCommandService.java
  src/main/java/kr/teammanagers/notice/application/command/NoticeCommandServiceImpl.java
  src/main/java/kr/teammanagers/notice/application/module/NoticeModuleService.java
  src/main/java/kr/teammanagers/notice/application/module/NoticeModuleServiceImpl.java
  src/main/java/kr/teammanagers/notice/application/query/NoticeQueryService.java
  src/main/java/kr/teammanagers/notice/application/query/NoticeQueryServiceImpl.java
  src/main/java/kr/teammanagers/notice/dto/request/CreateNotice.java
  src/main/java/kr/teammanagers/notice/presentation/NoticeController.java
  src/main/java/kr/teammanagers/team/application/module/TeamModuleService.java
  src/main/java/kr/teammanagers/team/application/module/TeamModuleServiceImpl.java
  src/main/java/kr/teammanagers/team/dto/request/CreateTeam.java
  src/main/java/kr/teammanagers/team/dto/request/CreateTeamComment.java
  src/main/java/kr/teammanagers/team/dto/request/CreateTeamPassword.java
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#77 [Feature] 내 투두리스트 조회 API 응답 필드 추가
  src/main/java/kr/teammanagers/todo/dto/MyTodoListDto.java
Labels: :recycle: Refactor, :large_blue_circle: 희수

#78 [Feature] 메모 개별 조회 API 구현
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/memo/application/command/MemoCommandService.java
  src/main/java/kr/teammanagers/memo/application/command/MemoCommandServiceImpl.java
  src/main/java/kr/teammanagers/memo/application/module/MemoModuleService.java
  src/main/java/kr/teammanagers/memo/application/module/MemoModuleServiceImpl.java
  src/main/java/kr/teammanagers/memo/application/query/MemoQueryService.java
  src/main/java/kr/teammanagers/memo/application/query/MemoQueryServiceImpl.java
  src/main/java/kr/teammanagers/memo/dto/response/GetMemo.java
  src/main/java/kr/teammanagers/memo/presentation/MemoController.java
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#80 [Feature] 팀 참가 로직 및 API 기능 구현
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/notice/application/command/NoticeCommandServiceImpl.java
  src/main/java/kr/teammanagers/team/application/command/TeamCommandService.java
  src/main/java/kr/teammanagers/team/application/command/TeamCommandServiceImpl.java
  src/main/java/kr/teammanagers/team/application/module/TeamModuleService.java
  src/main/java/kr/teammanagers/team/application/module/TeamModuleServiceImpl.java
  src/main/java/kr/teammanagers/team/application/query/TeamQueryService.java
  src/main/java/kr/teammanagers/team/application/query/TeamQueryServiceImpl.java
  src/main/java/kr/teammanagers/team/domain/TeamManage.java
  src/main/java/kr/teammanagers/team/dto/request/ValidatePassword.java
  src/main/java/kr/teammanagers/team/exception/validator/TeamMemberSizeValidator.java
  src/main/java/kr/teammanagers/team/presentation/TeamController.java
  src/main/java/kr/teammanagers/team/repository/TeamManageRepository.java
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#82 [Fix] 캘린더 알림 로직 수정
  src/main/java/kr/teammanagers/alarm/application/AlarmScheduler.java
Labels: :recycle: Refactor, :large_blue_circle: 희수

#81 [Feature] 투두 도메인 에러처리 및 서비스 레이어 분리
  src/main/java/kr/teammanagers/team/application/module/TeamModuleService.java
  src/main/java/kr/teammanagers/team/application/module/TeamModuleServiceImpl.java
  src/main/java/kr/teammanagers/todo/application/TodoCommandServiceImpl.java
  src/main/java/kr/teammanagers/todo/application/command/TodoCommandService.java
  src/main/java/kr/teammanagers/todo/application/command/TodoCommandServiceImpl.java
  src/main/java/kr/teammanagers/todo/application/module/TodoModuleService.java
  src/main/java/kr/teammanagers/todo/application/module/TodoModuleServiceImpl.java
  src/main/java/kr/teammanagers/todo/application/query/TodoQueryService.java
  src/main/java/kr/teammanagers/todo/application/query/TodoQueryServiceImpl.java
  src/main/java/kr/teammanagers/todo/dto/request/CreateTodo.java
  src/main/java/kr/teammanagers/todo/dto/request/UpdateTodo.java
  src/main/java/kr/teammanagers/todo/presentation/TodoRestController.java
  src/main/java/kr/teammanagers/todo/repository/TodoRepository.java
Labels: :bug: Bug, :recycle: Refactor, :large_blue_circle: 희수

#86 [Refactor] 멤버 도메인 파라미터 수정 로직 추가
  src/main/java/kr/teammanagers/auth/dto/OAuth2UserInfo.java
  src/main/java/kr/teammanagers/global/provider/AmazonS3Provider.java
  src/main/java/kr/teammanagers/member/application/MemberCommandServiceImpl.java
  src/main/java/kr/teammanagers/member/domain/Member.java
  src/main/java/kr/teammanagers/member/dto/request/UpdateProfile.java
  src/main/java/kr/teammanagers/member/dto/response/GetProfile.java
  src/main/java/kr/teammanagers/member/presentation/MemberController.java
  src/main/java/kr/teammanagers/team/application/command/TeamCommandService.java
  src/main/java/kr/teammanagers/team/application/command/TeamCommandServiceImpl.java
  src/main/java/kr/teammanagers/team/domain/Team.java
  src/main/java/kr/teammanagers/team/dto/request/UpdateTeam.java
  src/main/java/kr/teammanagers/team/presentation/TeamController.java
Labels: :recycle: Refactor, :green_circle: 승민

#87 [fix] 호출한 url로 인증 정보 전송
  src/main/java/kr/teammanagers/auth/handler/OAuth2SuccessHandler.java
Labels: :sparkles: Feature, :yellow_circle: 현수

#89 [Fix] 팀 참여 - 비밀번호 검증 로직 수정
  src/main/java/kr/teammanagers/team/application/command/TeamCommandServiceImpl.java
Labels: :bug: Bug, :green_circle: 승민

#90 [Fix] OAuth2SuccessHandler redirectUrl 변경
  src/main/java/kr/teammanagers/auth/handler/OAuth2SuccessHandler.java
Labels: :bug: Bug, :yellow_circle: 현수

#94 [Refactor] 내 프로필 조회 - 소셜타입 필드 추가
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/member/domain/Member.java
  src/main/java/kr/teammanagers/member/dto/SocialType.java
  src/main/java/kr/teammanagers/member/dto/response/GetProfile.java
Labels: :sparkles: Feature, :green_circle: 승민

#97 [Feature] 스케줄 도메인 레이어 분리 및 변경사항 반영
  src/main/java/kr/teammanagers/calendar/domain/Calendar.java
  src/main/java/kr/teammanagers/schedule/application/command/ScheduleCommandService.java
  src/main/java/kr/teammanagers/schedule/application/command/ScheduleCommandServiceImpl.java
  src/main/java/kr/teammanagers/schedule/application/module/ScheduleModuleService.java
  src/main/java/kr/teammanagers/schedule/application/module/ScheduleModuleServiceImpl.java
  src/main/java/kr/teammanagers/schedule/application/query/ScheduleQueryService.java
  src/main/java/kr/teammanagers/schedule/application/query/ScheduleQueryServiceImpl.java
  src/main/java/kr/teammanagers/schedule/presentation/ScheduleRestController.java
  src/main/java/kr/teammanagers/todo/application/module/TodoModuleServiceImpl.java
Labels: :recycle: Refactor, :large_blue_circle: 희수

#98 [Feature] 팀 도메인 관련 기능 추가 구현
  src/main/java/kr/teammanagers/alarm/domain/Alarm.java
  src/main/java/kr/teammanagers/calendar/domain/TeamCalendar.java
  src/main/java/kr/teammanagers/feedback/domain/Feedback.java
  src/main/java/kr/teammanagers/schedule/application/command/ScheduleCommandServiceImpl.java
  src/main/java/kr/teammanagers/schedule/application/query/ScheduleQueryServiceImpl.java
  src/main/java/kr/teammanagers/schedule/domain/Schedule.java
  src/main/java/kr/teammanagers/storage/domain/TeamData.java
  src/main/java/kr/teammanagers/team/application/command/TeamCommandService.java
  src/main/java/kr/teammanagers/team/application/command/TeamCommandServiceImpl.java
  src/main/java/kr/teammanagers/team/application/query/TeamQueryService.java
  src/main/java/kr/teammanagers/team/application/query/TeamQueryServiceImpl.java
  src/main/java/kr/teammanagers/team/dto/response/GetSimpleTeamMember.java
  src/main/java/kr/teammanagers/team/dto/response/GetTeamMember.java
  src/main/java/kr/teammanagers/team/presentation/TeamController.java
  src/main/java/kr/teammanagers/todo/application/module/TodoModuleServiceImpl.java
  src/main/java/kr/teammanagers/todo/domain/Todo.java
Labels: :sparkles: Feature, :green_circle: 승민

#100 [Fix] cascade 제거 및 캘린더 DTO 수정
  src/main/java/kr/teammanagers/alarm/domain/Alarm.java
  src/main/java/kr/teammanagers/calendar/application/CalendarQueryServiceImpl.java
  src/main/java/kr/teammanagers/calendar/domain/TeamCalendar.java
  src/main/java/kr/teammanagers/calendar/dto/CalendarDetailDto.java
  src/main/java/kr/teammanagers/feedback/domain/Feedback.java
  src/main/java/kr/teammanagers/schedule/domain/Schedule.java
  src/main/java/kr/teammanagers/storage/domain/TeamData.java
  src/main/java/kr/teammanagers/todo/domain/Todo.java
Labels: :bug: Bug, :large_blue_circle: 희수

#102 [Feature] 내 스케줄 조회 API 추가
  src/main/java/kr/teammanagers/schedule/application/query/ScheduleQueryService.java
  src/main/java/kr/teammanagers/schedule/application/query/ScheduleQueryServiceImpl.java
  src/main/java/kr/teammanagers/schedule/dto/ScheduleDto.java
  src/main/java/kr/teammanagers/schedule/dto/response/GetMySchedule.java
  src/main/java/kr/teammanagers/schedule/presentation/ScheduleRestController.java
Labels: :sparkles: Feature, :large_blue_circle: 희수

#105 [Fix] 팀 스케줄 계산 로직 수정
  src/main/java/kr/teammanagers/schedule/application/query/ScheduleQueryServiceImpl.java
Labels: :bug: Bug, :large_blue_circle: 희수

#103 [Refactor] 팀 나가기 기능 로직 수정
  src/main/java/kr/teammanagers/alarm/repository/AlarmRepository.java
  src/main/java/kr/teammanagers/calendar/repository/TeamCalendarRepository.java
  src/main/java/kr/teammanagers/member/application/MemberQueryServiceImpl.java
  src/main/java/kr/teammanagers/schedule/domain/Schedule.java
  src/main/java/kr/teammanagers/team/application/command/TeamCommandServiceImpl.java
  src/main/java/kr/teammanagers/todo/application/module/TodoModuleService.java
  src/main/java/kr/teammanagers/todo/application/module/TodoModuleServiceImpl.java
  src/main/java/kr/teammanagers/todo/repository/TodoRepository.java
Labels: :recycle: Refactor, :green_circle: 승민

#106 [FIX] storage user authentication fix
  src/main/java/kr/teammanagers/storage/application/StorageCommandService.java
  src/main/java/kr/teammanagers/storage/application/StorageCommandServiceImpl.java
  src/main/java/kr/teammanagers/storage/application/StorageQueryService.java
  src/main/java/kr/teammanagers/storage/application/StorageQueryServiceImpl.java
  src/main/java/kr/teammanagers/storage/presentation/StorageController.java
Labels: :bug: Bug, :yellow_circle: 현수

#108 [feat] IsnewUser method add
  src/main/java/kr/teammanagers/auth/Application/CustomOAuth2UserService.java
  src/main/java/kr/teammanagers/auth/dto/PrincipalDetails.java
  src/main/java/kr/teammanagers/auth/handler/OAuth2SuccessHandler.java
Labels: :sparkles: Feature, :yellow_circle: 현수

#107 [Feature] 스케줄 도메인 에러처리
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/schedule/application/command/ScheduleCommandServiceImpl.java
  src/main/java/kr/teammanagers/schedule/application/query/ScheduleQueryServiceImpl.java
  src/main/java/kr/teammanagers/schedule/dto/response/GetMySchedule.java
Labels: :sparkles: Feature, :large_blue_circle: 희수

#118 [FIX] teamData_title length fix
  src/main/java/kr/teammanagers/storage/domain/TeamData.java
Labels: :bug: Bug, :yellow_circle: 현수

#123 [Feature] 팀 스케줄 부분 조회 API 추가
  src/main/java/kr/teammanagers/schedule/application/query/ScheduleQueryService.java
  src/main/java/kr/teammanagers/schedule/application/query/ScheduleQueryServiceImpl.java
  src/main/java/kr/teammanagers/schedule/dto/request/GetPortionSchedule.java
  src/main/java/kr/teammanagers/schedule/dto/response/GetPortionScheduleResult.java
  src/main/java/kr/teammanagers/schedule/presentation/ScheduleRestController.java
Labels: :sparkles: Feature, :large_blue_circle: 희수

#125 [Refactor] 인증 도메인 통합 및 코드 리팩토링
  src/main/java/kr/teammanagers/auth/Application/CustomOAuth2UserService.java
  src/main/java/kr/teammanagers/auth/Application/CustomUserDetailsService.java
  src/main/java/kr/teammanagers/auth/Application/TokenService.java
  src/main/java/kr/teammanagers/auth/constant/AuthConstant.java
  src/main/java/kr/teammanagers/auth/dto/CustomUserDetails.java
  src/main/java/kr/teammanagers/auth/dto/OAuth2UserInfo.java
  src/main/java/kr/teammanagers/auth/dto/TokenDto.java
  src/main/java/kr/teammanagers/auth/filter/TokenAuthenticationFilter.java
  src/main/java/kr/teammanagers/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/kr/teammanagers/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/kr/teammanagers/auth/handler/OAuth2FailureHandler.java
  src/main/java/kr/teammanagers/auth/handler/OAuth2SuccessHandler.java
  src/main/java/kr/teammanagers/auth/jwt/domain/MemberToken.java
  src/main/java/kr/teammanagers/auth/jwt/repository/MemberTokenRepository.java
  src/main/java/kr/teammanagers/auth/presentation/AuthController.java
  src/main/java/kr/teammanagers/auth/provider/TokenProvider.java
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/global/config/SecurityConfig.java
  src/main/java/kr/teammanagers/global/constant/TokenKey.java
  src/main/java/kr/teammanagers/global/exception/AuthException.java
  src/main/java/kr/teammanagers/global/exception/CustomException.java
  src/main/java/kr/teammanagers/global/exception/ErrorCode.java
  src/main/java/kr/teammanagers/global/exception/ErrorResponse.java
  src/main/java/kr/teammanagers/global/exception/ExceptionAdvice.java
  src/main/java/kr/teammanagers/global/exception/GlobalExceptionHandler.java
  src/main/java/kr/teammanagers/global/exception/TokenException.java
  src/main/java/kr/teammanagers/global/exception/TokenExceptionFilter.java
  src/main/java/kr/teammanagers/member/application/module/MemberModuleService.java
  src/main/java/kr/teammanagers/member/application/module/MemberModuleServiceImpl.java
  src/main/java/kr/teammanagers/member/domain/Member.java
  src/main/java/kr/teammanagers/schedule/application/command/ScheduleCommandServiceImpl.java
  src/main/java/kr/teammanagers/schedule/application/query/ScheduleQueryService.java
  src/main/resources/application.yml
Labels: :recycle: Refactor, :green_circle: 승민
