Repository Teammanagers/BackEnd, pull requests merged in 2024-07, with the labels that each got.

#2 [CI/CD] 배포 자동화, 환경 변수 설정 및 모니터링 API 추가
  .github/workflows/deploy.yml
  src/main/java/kr/teammanagers/TeammanagersApplication.java
  src/main/java/kr/teammanagers/common/presentation/HealthCheckController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :construction_worker: CI/CD, :green_circle: 승민

#3 [CI/CD] Dockerfile 추가
  Dockerfile
Labels: :construction_worker: CI/CD, :green_circle: 승민

#5 [Chore] 프로젝트 세팅 마무리
  .gitignore
  build.gradle
  src/main/java/kr/teammanagers/TeammanagersApplication.java
  src/main/java/kr/teammanagers/alarm/domain/Alarm.java
  src/main/java/kr/teammanagers/calendar/domain/AvailableTime.java
  src/main/java/kr/teammanagers/calendar/domain/TimeTable.java
  src/main/java/kr/teammanagers/common/AuditingField.java
  src/main/java/kr/teammanagers/common/EntityStatus.java
  src/main/java/kr/teammanagers/common/Status.java
  src/main/java/kr/teammanagers/common/payload/code/ApiPayload.java
  src/main/java/kr/teammanagers/common/payload/code/ExceptionAdvice.java
  src/main/java/kr/teammanagers/common/payload/code/GeneralException.java
  src/main/java/kr/teammanagers/common/payload/code/base/BaseCode.java
  src/main/java/kr/teammanagers/common/payload/code/base/ErrorBaseCode.java
  src/main/java/kr/teammanagers/common/payload/code/dto/ErrorReasonDto.java
  src/main/java/kr/teammanagers/common/payload/code/dto/ReasonDto.java
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/common/payload/code/status/SuccessStatus.java
  src/main/java/kr/teammanagers/feedback/domain/Feedback.java
  src/main/java/kr/teammanagers/global/config/AmazonConfig.java
  src/main/java/kr/teammanagers/global/config/QueryDslConfig.java
  src/main/java/kr/teammanagers/global/config/RedisConfig.java
  src/main/java/kr/teammanagers/global/constant/AmazonConstant.java
  src/main/java/kr/teammanagers/global/provider/AmazonS3Provider.java
  src/main/java/kr/teammanagers/member/domain/Member.java
  src/main/java/kr/teammanagers/member/repository/MemberQueryDsl.java
  src/main/java/kr/teammanagers/member/repository/MemberQueryDslImpl.java
  src/main/java/kr/teammanagers/member/repository/MemberRepository.java
  src/main/java/kr/teammanagers/memo/domain/Memo.java
  src/main/java/kr/teammanagers/notice/domain/Notice.java
  src/main/java/kr/teammanagers/schedule/domain/Schedule.java
  src/main/java/kr/teammanagers/schedule/domain/TeamSchedule.java
  src/main/java/kr/teammanagers/storage/domain/TeamData.java
  src/main/java/kr/teammanagers/tag/domain/ConfidentRole.java
  src/main/java/kr/teammanagers/tag/domain/Tag.java
  src/main/java/kr/teammanagers/tag/domain/TagMemo.java
  src/main/java/kr/teammanagers/tag/domain/TagTeam.java
  src/main/java/kr/teammanagers/tag/domain/TeamRole.java
  src/main/java/kr/teammanagers/team/domain/Team.java
  src/main/java/kr/teammanagers/team/domain/TeamManage.java
  src/main/java/kr/teammanagers/term/domain/CheckedTerms.java
  src/main/java/kr/teammanagers/todo/domain/Todo.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :wrench: Configuration, :green_circle: 승민

#9 [Feature]: 사용자 도메인 구현 완료
  src/main/java/kr/teammanagers/alarm/domain/Alarm.java
  src/main/java/kr/teammanagers/common/MultipartJackson2HttpMessageConverter.java
  src/main/java/kr/teammanagers/common/payload/code/ApiPayload.java
  src/main/java/kr/teammanagers/global/constant/AmazonConstant.java
  src/main/java/kr/teammanagers/global/provider/AmazonS3Provider.java
  src/main/java/kr/teammanagers/member/application/MemberService.java
  src/main/java/kr/teammanagers/member/domain/Comment.java
  src/main/java/kr/teammanagers/member/domain/Member.java
  src/main/java/kr/teammanagers/member/dto/SimplePortfolioDto.java
  src/main/java/kr/teammanagers/member/dto/request/UpdateProfile.java
  src/main/java/kr/teammanagers/member/dto/response/GetMemberTeam.java
  src/main/java/kr/teammanagers/member/dto/response/GetPortfolio.java
  src/main/java/kr/teammanagers/member/dto/response/GetProfile.java
  src/main/java/kr/teammanagers/member/dto/response/GetSimplePortfolioList.java
  src/main/java/kr/teammanagers/member/presentation/MemberController.java
  src/main/java/kr/teammanagers/member/repository/CommentRepository.java
  src/main/java/kr/teammanagers/member/repository/MemberQueryDslImpl.java
  src/main/java/kr/teammanagers/schedule/domain/Calendar.java
  src/main/java/kr/teammanagers/schedule/domain/TeamCalendar.java
  src/main/java/kr/teammanagers/storage/dto/StorageDto.java
  src/main/java/kr/teammanagers/storage/repository/TeamDataRepository.java
  src/main/java/kr/teammanagers/tag/application/TagModuleService.java
  src/main/java/kr/teammanagers/tag/domain/ConfidentRole.java
  src/main/java/kr/teammanagers/tag/dto/TagDto.java
  src/main/java/kr/teammanagers/tag/repository/ConfidentRoleRepository.java
  src/main/java/kr/teammanagers/tag/repository/TagRepository.java
  src/main/java/kr/teammanagers/tag/repository/TagTeamRepository.java
  src/main/java/kr/teammanagers/team/dto/CommentDto.java
  src/main/java/kr/teammanagers/team/dto/TeamDto.java
  src/main/java/kr/teammanagers/team/repository/TeamManageRepository.java
  src/main/java/kr/teammanagers/team/repository/TeamRepository.java
  src/main/java/kr/teammanagers/team/repository/TeamRoleRepository.java
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#13 [Refactor] Exception 패키지 생성 및 파일 위치 변경
  src/main/java/kr/teammanagers/global/exception/ExceptionAdvice.java
  src/main/java/kr/teammanagers/global/exception/GeneralException.java
Labels: :recycle: Refactor, :yellow_circle: 현수

#15 [Feature] 약관 도메인 구현 완료
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/term/application/TermCommandService.java
  src/main/java/kr/teammanagers/term/application/TermCommandServiceImpl.java
  src/main/java/kr/teammanagers/term/domain/CheckedTerms.java
  src/main/java/kr/teammanagers/term/dto/CreateTerms.java
  src/main/java/kr/teammanagers/term/presentation/TermRestController.java
  src/main/java/kr/teammanagers/term/repository/TermQueryDsl.java
  src/main/java/kr/teammanagers/term/repository/TermQueryDslImpl.java
  src/main/java/kr/teammanagers/term/repository/TermRepository.java
Labels: :sparkles: Feature, :large_blue_circle: 희수

#16 [Feature] 태그 도메인 구현 완료
  src/main/java/kr/teammanagers/global/exception/ExceptionAdvice.java
  src/main/java/kr/teammanagers/global/exception/GeneralException.java
  src/main/java/kr/teammanagers/tag/application/TagService.java
  src/main/java/kr/teammanagers/tag/domain/TagTeam.java
  src/main/java/kr/teammanagers/tag/domain/TeamRole.java
  src/main/java/kr/teammanagers/tag/presentation/TagController.java
  src/main/java/kr/teammanagers/tag/request/CreateRoleTag.java
  src/main/java/kr/teammanagers/tag/request/UpdateRoleTag.java
  src/main/java/kr/teammanagers/tag/request/UpdateTeamTag.java
  src/main/java/kr/teammanagers/term/application/TermCommandService.java
  src/main/java/kr/teammanagers/term/application/TermCommandServiceImpl.java
  src/main/java/kr/teammanagers/term/domain/CheckedTerms.java
  src/main/java/kr/teammanagers/term/dto/CreateTerms.java
  src/main/java/kr/teammanagers/term/presentation/TermRestController.java
Labels: :sparkles: Feature, :green_circle: 승민

#17 [Feature] 투두 도메인 구현 완료
  src/main/java/kr/teammanagers/common/payload/code/status/ErrorStatus.java
  src/main/java/kr/teammanagers/tag/dto/TagDto.java
  src/main/java/kr/teammanagers/tag/repository/TeamRoleRepository.java
  src/main/java/kr/teammanagers/todo/application/TodoCommandService.java
  src/main/java/kr/teammanagers/todo/application/TodoCommandServiceImpl.java
  src/main/java/kr/teammanagers/todo/application/TodoQueryService.java
  src/main/java/kr/teammanagers/todo/application/TodoQueryServiceImpl.java
  src/main/java/kr/teammanagers/todo/domain/Todo.java
  src/main/java/kr/teammanagers/todo/dto/TodoDto.java
  src/main/java/kr/teammanagers/todo/dto/TodoListDto.java
  src/main/java/kr/teammanagers/todo/dto/request/CreateTodo.java
  src/main/java/kr/teammanagers/todo/dto/request/UpdateTodo.java
  src/main/java/kr/teammanagers/todo/dto/response/GetTodoList.java
  src/main/java/kr/teammanagers/todo/presentation/TodoRestController.java
  src/main/java/kr/teammanagers/todo/repository/TodoQueryDsl.java
  src/main/java/kr/teammanagers/todo/repository/TodoQueryDslImpl.java
  src/main/java/kr/teammanagers/todo/repository/TodoRepository.java
Labels: :sparkles: Feature, :recycle: Refactor, :large_blue_circle: 희수

#19 [Feat]: 멤버 클래스 providerId 변수 및 findByProviderId 메소드 구현
  build.gradle
  src/main/java/kr/teammanagers/auth/domain/redis/entity/Token.java
  src/main/java/kr/teammanagers/auth/domain/redis/repository/TokenRepository.java
  src/main/java/kr/teammanagers/auth/dto/OAuth2UserInfo.java
  src/main/java/kr/teammanagers/auth/dto/PrincipalDetails.java
  src/main/java/kr/teammanagers/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/kr/teammanagers/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/kr/teammanagers/auth/handler/OAuth2FailureHandler.java
  src/main/java/kr/teammanagers/auth/handler/OAuth2SuccessHandler.java
  src/main/java/kr/teammanagers/auth/service/CustomOAuth2UserService.java
  src/main/java/kr/teammanagers/auth/service/TokenService.java
  src/main/java/kr/teammanagers/global/config/SecurityConfig.java
  src/main/java/kr/teammanagers/global/constant/TokenKey.java
  src/main/java/kr/teammanagers/global/exception/AuthException.java
  src/main/java/kr/teammanagers/global/exception/CustomException.java
  src/main/java/kr/teammanagers/global/exception/ErrorCode.java
  src/main/java/kr/teammanagers/global/exception/ErrorResponse.java
  src/main/java/kr/teammanagers/global/exception/GlobalExceptionHandler.java
  src/main/java/kr/teammanagers/global/exception/TokenAuthenticationFilter.java
  src/main/java/kr/teammanagers/global/exception/TokenException.java
  src/main/java/kr/teammanagers/global/exception/TokenExceptionFilter.java
  src/main/java/kr/teammanagers/global/provider/TokenProvider.java
  src/main/java/kr/teammanagers/member/domain/Member.java
  src/main/java/kr/teammanagers/member/repository/MemberRepository.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: :sparkles: Feature, :yellow_circle: 현수

#23 [Feature] 공지 도메인 구현 완료 및 코드 포맷 정리
  src/main/java/kr/teammanagers/member/application/MemberService.java
  src/main/java/kr/teammanagers/member/dto/response/GetProfile.java
  src/main/java/kr/teammanagers/member/presentation/MemberController.java
  src/main/java/kr/teammanagers/notice/application/NoticeService.java
  src/main/java/kr/teammanagers/notice/dto/NoticeDto.java
  src/main/java/kr/teammanagers/notice/dto/request/CreateNotice.java
  src/main/java/kr/teammanagers/notice/dto/response/GetNoticeList.java
  src/main/java/kr/teammanagers/notice/presentation/NoticeController.java
  src/main/java/kr/teammanagers/notice/repository/NoticeRepository.java
  src/main/java/kr/teammanagers/tag/dto/TagDto.java
  src/main/java/kr/teammanagers/tag/presentation/TagController.java
  src/main/java/kr/teammanagers/todo/application/TodoCommandServiceImpl.java
  src/main/java/kr/teammanagers/todo/dto/request/CreateTodo.java
  src/main/java/kr/teammanagers/todo/dto/request/UpdateTodo.java
Labels: :sparkles: Feature, :green_circle: 승민

#25 [Feature] 메모 도메인 구현 완료
  src/main/java/kr/teammanagers/memo/application/MemoService.java
  src/main/java/kr/teammanagers/memo/domain/Memo.java
  src/main/java/kr/teammanagers/memo/dto/MemoDto.java
  src/main/java/kr/teammanagers/memo/dto/request/CreateMemo.java
  src/main/java/kr/teammanagers/memo/dto/request/UpdateMemo.java
  src/main/java/kr/teammanagers/memo/dto/response/GetMemoList.java
  src/main/java/kr/teammanagers/memo/presentation/MemoController.java
  src/main/java/kr/teammanagers/memo/repository/MemoRepository.java
  src/main/java/kr/teammanagers/tag/application/TagModuleService.java
  src/main/java/kr/teammanagers/tag/domain/TagMemo.java
  src/main/java/kr/teammanagers/tag/repository/TagMemoRepository.java
Labels: :sparkles: Feature, :green_circle: 승민
